platform:ios,'8.0'

inhibit_all_warnings!
use_frameworks!


target "Demo" do

source 'https://github.com/CocoaPods/Specs'

pod 'Resources', :path => '../'

end

#切换pod源之后，pod update --no-repo-update即可
